project: 
  type: website
  output-dir: docs

website:
  title: "Anissa Waller Del Valle: Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        file: aboutme.qmd
      - text: "Projects"
        menu:
          - text: "Starter Analysis Exercise"
            file: starter-analysis-exercise/starter-analysis-exercise.qmd
    right:
      - icon: github 
        href: https://github.com/anissawdv/anissawallerdelvalle-portfolio        
format:
  html:
    theme: lumen
    highlight: zenburn
    css: styles.css
    toc: FALSE